### PR TITLE
PROD-257: add test for cb_conference_auth

### PR DESCRIPTION
**Pull request by icehess**
Add test for `cb_conference_auth`.

### Required PR
add conference auth: https://github.com/2600hz/kazoo-crossbar/pull/67
* fix a crash when adding an account under reseller: https://github.com/2600hz/kazoo-core/pull/117

### Related PRs
name is now required: https://github.com/2600hz/kazoo-properly/pull/28

### CODE REVIEW

**Comment by icehess** [comment]
Other than dependency on other PRs, cb_conference_auth test should still failed because scope is not working as intended.

**Comment by jamesaimonetti** [comment]
@icehess let's comment out the test until scopes are addressed. We can't merge this if it will definitely fail each run.

**Comment by icehess** [comment]
Don't merge this until the scope is fixed! This PR is just for this to block conference link until we fix scopes.

**Comment by sanjeevie6353** [comment]
@icehess this PR has conflicts with the latest master branch. Is this still relevant?

**Pull request closed without merging**
