### PR TITLE
KZOO-301: Add test case to test failed login attempts for cb_user_auth

### PR DESCRIPTION
**Pull request by dhuynh-Kazoo**
The auth token is added for some authentication modules: cb_user_auth/cb_basic_auth/cb_conference_auth... Sometimes filling mechanism doesn't synchronize between the standard token and auth token(standard tokens ảefilled sooner), which makes seq_auth_attempts test fail because of the exhausted auth token.

### CODE REVIEW

**Comment by dhuynh-Kazoo** [comment]
This PR will add 2 cases to `properly` for `seq_auth_attempts.erl` one is for user_auth(pushed) and one is for api_auth(will push soon).

Main implementation for locking many failed login attempts: - https://github.com/2600hz/kazoo-crossbar/pull/467
Utility function from kazoo_token_buckets: https://github.com/2600hz/kazoo-core/pull/663

**Comment by icehess** [comment]
Required PRs:
- https://github.com/2600hz/kazoo-crossbar/pull/467
- https://github.com/2600hz/kazoo-core/pull/663
- https://github.com/2600hz/kazoo-properly/pull/150
- https://github.com/2600hz/kazoo-desktop/pull/25

**Comment by icehess** [comment]
@dhuynh-Kazoo Hey, can you resolve the conflict here please?

**Comment by jamesaimonetti** [comment]
Test fails because it can't set the system config for locking accounts:

```
2023-09-08T15:26:03.754530-07:00 compy64 2600hz[2757986]: |0000000000|pqc_cb_api:468(<0.6735.3>) fail to config log in on failed attempts with error {"version":"5.0.1","auth_token":"{AUTH_TOKEN}","tokens": "consumed":0,"remaining":0},"timestamp":"2023-09-08T22:26:03Z","request_id":"14bd692c63-63861431163682","node":"7g_QhLmS3l7GeKv5iD7sig","metadata":{},"data":{"default.auth_modules.cb_conference_auth":{"additionalProperties":{"value":{"cb_user_auth":"token_auth_expiry_s":3600,"scopes":"crossbar"],"log_successful_attempts":true,"log_failed_attempts":true,"enabled":true},"cb_ip_auth":{"token_auth_expiry_s":3600,"scopes":"crossbar"],"log_successful_attempts":false,"log_failed_attempts":true,"enabled":true},"cb_conference_auth":{"token_auth_expiry_s":"infinity","scopes":"crossbar"],"log_successful_attempts":false,"log_failed_attempts":true,"enabled":true},"cb_auth": {"token_auth_expiry_s":3600,"scopes":"crossbar"],"log_successful_attempts":false,"log_failed_attempts":true,"enabled":true},"cb_api_auth":{"token_auth_expiry_s":3600,"scopes":"crossbar"],"log_successful_attempts":false,"log_failed_attempts":true,"enabled":true}},"message":"Strict checking of data is enabled; only include schema-defined properties"}}},"error":"400","message":"validation error","status":"error"}                                                   
```

Have you seen this test pass successfully on your local environment?

**Comment by jamesaimonetti** [comment]
Add some cleanup commits, please check them

**Comment by dhuynh-Kazoo** [comment]
hi @jamesaimonetti, please pull the latest code of `crossbar and properly` then try again. I think they should work now.

**Pull request merged**
